# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57d7508fb61211f50a6bf1e9e39a84de3949463d60f6f0918f9a964d72197d79e66d887c3d15591bebb686b808927f0e2e0053efad4fd7066c25cf3bed98021c

test:
  secret_key_base: 722aea5d3b24dd69b5a71a5da8890b55a3ca878677902e2bf630e1ef587b5cd56c64979def47b4d4c95926a944cefb7f6108f19d568b3c7b4b4d8f17827c3638

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
